# pnpm workspace 配置
# 用于管理 CLI 项目依赖版本

gitChecks: false
registry: https://registry.npmjs.org/

catalogs:
  build:
    chalk: ^5.3.0
    commander: ^12.1.0
    ejs: ^3.1.10
    fs-extra: ^11.3.0
    inquirer: ^12.0.0
    lodash-es: ^4.17.21
    ora: ^8.1.1
    yaml: ^2.6.0
  dev:
    '@commitlint/cli': ^19.8.0
    '@commitlint/config-conventional': ^19.8.0
    '@moluoxixi/eslint-config': latest
    commitizen: ^4.3.1
    cz-customizable: ^7.4.0
    eslint: ^9.5.0
    husky: ^9.1.7
    lint-staged: ^15.5.1
    tsx: ^4.20.5
    typescript: ~5.8.0
  type:
    '@types/ejs': ^3.1.5
    '@types/fs-extra': ^11.0.4
    '@types/inquirer': ^9.0.7
    '@types/lodash-es': ^4.17.12
    '@types/node': ^22.14.0
