/**
 * 测试脚本
 * 生成 Vue (Element Plus / Ant Design Vue) 和 React (Ant Design) 测试项目，启用所有功能
 */

import type { ProjectConfig } from './types/index.ts'
import { execSync } from 'node:child_process'
import * as process from 'node:process'
import fs from 'fs-extra'
import { generateProject } from './generators/project'

/**
 * 获取测试目录路径
 */
const testDir = `${process.cwd().replace(/vite-cli$/, '')}vite-cli-test`

/**
 * Vue + Element Plus 测试配置（启用所有功能）
 */
const vueElementConfig: ProjectConfig = {
  projectName: 'vue-element',
  description: 'Vue + Element Plus test project generated by vite-cli',
  author: 'vite-cli',
  framework: 'vue',
  uiLibrary: 'element-plus',
  routeMode: 'file-system',
  i18n: true,
  qiankun: true,
  sentry: true,
  packageManager: 'pnpm',
  targetDir: `${testDir}/vue-element`,
}

/**
 * Vue + Ant Design Vue 测试配置（启用所有功能）
 */
const vueAntdConfig: ProjectConfig = {
  projectName: 'vue-antd',
  description: 'Vue + Ant Design Vue test project generated by vite-cli',
  author: 'vite-cli',
  framework: 'vue',
  uiLibrary: 'ant-design-vue',
  routeMode: 'file-system',
  i18n: true,
  qiankun: true,
  sentry: true,
  packageManager: 'pnpm',
  targetDir: `${testDir}/vue-antd`,
}

/**
 * React + Ant Design 测试配置（启用所有功能）
 */
const reactAntdConfig: ProjectConfig = {
  projectName: 'react-antd',
  description: 'React + Ant Design test project generated by vite-cli',
  author: 'vite-cli',
  framework: 'react',
  uiLibrary: 'ant-design',
  routeMode: 'file-system',
  i18n: true,
  qiankun: true,
  sentry: true,
  packageManager: 'pnpm',
  targetDir: `${testDir}/react-antd`,
}

/**
 * 清空测试目录
 */
function cleanTestDir(): void {
  console.log('🧹 Cleaning test directory...')
  if (fs.existsSync(testDir)) {
    try {
      // 尝试使用 fs-extra 删除
      fs.removeSync(testDir)
      console.log(`   Removed: ${testDir}`)
    }
    catch {
      // 如果 fs-extra 失败，使用系统命令强制删除（Windows）
      console.log('   Using system command to remove directory...')
      try {
        execSync(`rd /s /q "${testDir}"`, { stdio: 'ignore', shell: 'cmd.exe' })
        console.log(`   Removed: ${testDir}`)
      }
      catch {
        console.warn('   Warning: Could not fully clean directory, will overwrite files')
      }
    }
  }
  fs.ensureDirSync(testDir)
  console.log('✅ Test directory cleaned!\n')
}

/**
 * 安装项目依赖
 * @param projectDir 项目目录
 * @param projectName 项目名称
 */
function installDependencies(projectDir: string, projectName: string): void {
  console.log(`📦 Installing dependencies for ${projectName}...`)
  try {
    execSync('pnpm install', {
      cwd: projectDir,
      stdio: 'inherit',
    })
    console.log(`✅ ${projectName} dependencies installed!\n`)
  }
  catch (error) {
    console.error(`❌ Failed to install dependencies for ${projectName}`)
    throw error
  }
}

/**
 * 运行项目类型检查
 * @param projectDir 项目目录
 * @param projectName 项目名称
 */
function testTypeCheck(projectDir: string, projectName: string): void {
  console.log(`🚀 Testing ${projectName} type-check...`)
  try {
    execSync('pnpm type-check', {
      cwd: projectDir,
      stdio: 'inherit',
    })
    console.log(`✅ ${projectName} type-check passed!\n`)
  }
  catch (error) {
    console.error(`❌ ${projectName} type-check failed`)
    throw error
  }
}

/**
 * 生成单个项目
 * @param config 项目配置
 * @param name 项目显示名称
 */
async function generateSingleProject(config: ProjectConfig, name: string): Promise<void> {
  console.log(`📦 Generating ${name} project...`)
  console.log('Configuration:')
  console.log(`  Framework: ${config.framework}`)
  console.log(`  UI Library: ${config.uiLibrary}`)
  console.log(`  Route Mode: ${config.routeMode}`)
  console.log(`  i18n: ${config.i18n}`)
  console.log(`  Qiankun: ${config.qiankun}`)
  console.log(`  Sentry: ${config.sentry}`)
  console.log(`  Target: ${config.targetDir}\n`)

  await generateProject(config)
  console.log(`✅ ${name} project generated successfully!\n`)
}

/**
 * 运行测试
 */
async function runTest() {
  try {
    console.log('🚀 Starting test project generation...\n')

    // 清空测试目录
    cleanTestDir()

    // 生成所有项目
    await generateSingleProject(vueElementConfig, 'Vue + Element Plus')
    await generateSingleProject(vueAntdConfig, 'Vue + Ant Design Vue')
    await generateSingleProject(reactAntdConfig, 'React + Ant Design')

    console.log('🎉 All test projects generated successfully!')
    console.log(`\n📁 Vue + Element Plus: ${vueElementConfig.targetDir}`)
    console.log(`📁 Vue + Ant Design Vue: ${vueAntdConfig.targetDir}`)
    console.log(`📁 React + Ant Design: ${reactAntdConfig.targetDir}`)

    // 安装依赖并测试
    console.log(`\n${'='.repeat(50)}`)
    console.log('📦 Installing dependencies and testing...')
    console.log(`${'='.repeat(50)}\n`)

    // 安装所有项目依赖
    installDependencies(vueElementConfig.targetDir, 'Vue + Element Plus')
    installDependencies(vueAntdConfig.targetDir, 'Vue + Ant Design Vue')
    installDependencies(reactAntdConfig.targetDir, 'React + Ant Design')

    // 测试所有项目
    testTypeCheck(vueElementConfig.targetDir, 'Vue + Element Plus')
    testTypeCheck(vueAntdConfig.targetDir, 'Vue + Ant Design Vue')
    testTypeCheck(reactAntdConfig.targetDir, 'React + Ant Design')

    console.log(`\n${'='.repeat(50)}`)
    console.log('🎉 All tests passed!')
    console.log('='.repeat(50))
  }
  catch (error) {
    console.error('\n❌ Error:', error)
    process.exit(1)
  }
}

runTest()
