/**
 * 测试脚本
 * 同时生成 Vue 和 React 测试项目，启用所有功能
 */

import type { ProjectConfig } from './types/index.ts'
import { execSync } from 'node:child_process'
import * as process from 'node:process'
import fs from 'fs-extra'
import { generateProject } from './generators/project'

/**
 * 获取测试目录路径
 */
const testDir = `${process.cwd().replace(/vite-cli$/, '')}vite-cli-test`

/**
 * Vue 测试配置（启用所有功能）
 */
const vueTestConfig: ProjectConfig = {
  projectName: 'vue',
  description: 'Vue test project generated by vite-cli',
  author: 'vite-cli',
  framework: 'vue',
  uiLibrary: 'element-plus',
  routeMode: 'file-system',
  i18n: true,
  qiankun: true,
  sentry: true,
  packageManager: 'pnpm',
  targetDir: `${testDir}/vue`,
}

/**
 * React 测试配置（启用所有功能）
 */
const reactTestConfig: ProjectConfig = {
  projectName: 'react',
  description: 'React test project generated by vite-cli',
  author: 'vite-cli',
  framework: 'react',
  uiLibrary: 'ant-design',
  routeMode: 'file-system',
  i18n: true,
  qiankun: true,
  sentry: true,
  packageManager: 'pnpm',
  targetDir: `${testDir}/react`,
}

/**
 * 清空测试目录
 */
function cleanTestDir(): void {
  console.log('🧹 Cleaning test directory...')
  if (fs.existsSync(testDir)) {
    try {
      // 尝试使用 fs-extra 删除
      fs.removeSync(testDir)
      console.log(`   Removed: ${testDir}`)
    }
    catch {
      // 如果 fs-extra 失败，使用系统命令强制删除（Windows）
      console.log('   Using system command to remove directory...')
      try {
        execSync(`rd /s /q "${testDir}"`, { stdio: 'ignore', shell: 'cmd.exe' })
        console.log(`   Removed: ${testDir}`)
      }
      catch {
        console.warn('   Warning: Could not fully clean directory, will overwrite files')
      }
    }
  }
  fs.ensureDirSync(testDir)
  console.log('✅ Test directory cleaned!\n')
}

/**
 * 安装项目依赖
 * @param projectDir 项目目录
 * @param projectName 项目名称
 */
function installDependencies(projectDir: string, projectName: string): void {
  console.log(`📦 Installing dependencies for ${projectName}...`)
  try {
    execSync('pnpm install', {
      cwd: projectDir,
      stdio: 'inherit',
    })
    console.log(`✅ ${projectName} dependencies installed!\n`)
  }
  catch (error) {
    console.error(`❌ Failed to install dependencies for ${projectName}`)
    throw error
  }
}

/**
 * 运行项目开发服务器测试
 * @param projectDir 项目目录
 * @param projectName 项目名称
 */
function testDevServer(projectDir: string, projectName: string): void {
  console.log(`🚀 Testing ${projectName} dev server (will start and stop)...`)
  try {
    // 使用 type-check 来验证 TypeScript 编译
    execSync('pnpm type-check', {
      cwd: projectDir,
      stdio: 'inherit',
    })
    console.log(`✅ ${projectName} type-check passed!\n`)
  }
  catch (error) {
    console.error(`❌ ${projectName} type-check failed`)
    throw error
  }
}

/**
 * 运行测试
 */
async function runTest() {
  try {
    console.log('🚀 Starting test project generation...\n')

    // 清空测试目录
    cleanTestDir()

    // 生成 Vue 项目
    console.log('📦 Generating Vue project...')
    console.log('Configuration:')
    console.log(`  Framework: ${vueTestConfig.framework}`)
    console.log(`  UI Library: ${vueTestConfig.uiLibrary}`)
    console.log(`  Route Mode: ${vueTestConfig.routeMode}`)
    console.log(`  i18n: ${vueTestConfig.i18n}`)
    console.log(`  Qiankun: ${vueTestConfig.qiankun}`)
    console.log(`  Sentry: ${vueTestConfig.sentry}`)
    console.log(`  Target: ${vueTestConfig.targetDir}\n`)

    await generateProject(vueTestConfig)
    console.log('✅ Vue project generated successfully!\n')

    // 生成 React 项目
    console.log('📦 Generating React project...')
    console.log('Configuration:')
    console.log(`  Framework: ${reactTestConfig.framework}`)
    console.log(`  UI Library: ${reactTestConfig.uiLibrary}`)
    console.log(`  Route Mode: ${reactTestConfig.routeMode}`)
    console.log(`  i18n: ${reactTestConfig.i18n}`)
    console.log(`  Qiankun: ${reactTestConfig.qiankun}`)
    console.log(`  Sentry: ${reactTestConfig.sentry}`)
    console.log(`  Target: ${reactTestConfig.targetDir}\n`)

    await generateProject(reactTestConfig)
    console.log('✅ React project generated successfully!\n')

    console.log('🎉 All test projects generated successfully!')
    console.log(`\n📁 Vue project: ${vueTestConfig.targetDir}`)
    console.log(`📁 React project: ${reactTestConfig.targetDir}`)

    // 安装依赖并测试
    console.log(`\n${'='.repeat(50)}`)
    console.log('📦 Installing dependencies and testing...')
    console.log(`${'='.repeat(50)}\n`)

    // 安装 Vue 项目依赖
    installDependencies(vueTestConfig.targetDir, 'Vue')

    // 安装 React 项目依赖
    installDependencies(reactTestConfig.targetDir, 'React')

    // 测试 Vue 项目
    testDevServer(vueTestConfig.targetDir, 'Vue')

    // 测试 React 项目
    testDevServer(reactTestConfig.targetDir, 'React')

    console.log(`\n${'='.repeat(50)}`)
    console.log('🎉 All tests passed!')
    console.log('='.repeat(50))
  }
  catch (error) {
    console.error('\n❌ Error:', error)
    process.exit(1)
  }
}

runTest()
