# pnpm workspace 配置
# 用于管理项目依赖版本

gitChecks: false
registry: https://registry.npmjs.org/

catalogs:
  build:
    "@moluoxixi/ajax-package": latest
    "@moluoxixi/class-names": latest
    crypto-js: ^4.2.0
    dayjs: ^1.11.13
    lodash-es: ^4.17.21
    pinia: ^2.3.0
    pinia-plugin-persistedstate: ^4.2.0
    radash: ^12.1.0
    uuid: ^11.1.0
    vue: ^3.5.13
    vue-router: ^4.5.0
  dev:
    "@commitlint/cli": ^19.8.0
    "@commitlint/config-conventional": ^19.8.0
    "@moluoxixi/ajax-package": latest
    "@moluoxixi/css-module-global-root-plugin": latest
    "@moluoxixi/eslint-config": latest
    "@moluoxixi/vite-config": latest
    "@vue-macros/volar": ^3.0.0-beta.15
    autoprefixer: ^10.4.20
    commitizen: ^4.3.1
    compressing: ^1.10.1
    cz-customizable: ^7.4.0
    dotenv: ^16.5.0
    eslint: ^9.22.0
    eslint-plugin-format: ^1.0.1
    husky: ^9.1.7
    jiti: ^2.4.2
    lint-staged: ^15.5.1
    postcss: ^8.5.3
    sass: ^1.87.0
    sass-embedded: ^1.87.0
    sass-loader: ^16.0.5
    tailwindcss: ^4.0.0
    tsx: ^4.19.2
    typescript: ~5.8.0
    vite: ^6.2.4
    vue-tsc: ^2.2.8
  type:
    "@types/crypto-js": ^4.2.2
    "@types/lodash-es": ^4.17.12
    "@types/node": ^22.14.0
    "@types/uuid": ^10.0.0

